title: superfuckingduper.com
logo: /assets/img/logo.png
description:
show_downloads: true
google_analytics:
remote_theme: pages-themes/tactile@v0.2.0
paginate: 1
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
